# Generated by Django 5.0.6 on 2024-07-03 18:55

import authentication.utils
import django.db.models.deletion
import django.utils.timezone
import payments.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.IntegerField(validators=[payments.utils.validate_pan])),
                ('expire_month', models.IntegerField(validators=[payments.utils.validate_expire_month])),
                ('expire_year', models.IntegerField(validators=[payments.utils.validate_expire_year])),
                ('holder_full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=12, validators=[authentication.utils.username_validation])),
                ('balance', models.PositiveIntegerField(default=0)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=260, null=True)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_key', models.UUIDField(default=uuid.uuid4)),
                ('otp_code', models.IntegerField(default=authentication.utils.generate_otp_code)),
                ('phone_number', models.IntegerField(validators=[authentication.utils.username_validation])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[(1, 'active'), (2, 'expired'), (3, 'canceled')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('expired_at', models.DateField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
