# Generated by Django 5.0.6 on 2024-07-03 18:55

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_advertise', models.CharField(max_length=50)),
                ('movie_number', models.PositiveIntegerField(default=0)),
                ('qr_image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13, validators=[base.utils.phone_number_validation])),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13, validators=[base.utils.phone_number_validation])),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Sent_to_check'), (2, 'In_progress'), (3, 'Checked')], default=1)),
                ('is_solved', models.BooleanField(default=False)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
